# Generated by Django 3.2.13 on 2022-04-29 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('category', models.CharField(default='other', max_length=15)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cover', models.ImageField(blank=True, upload_to='books_covers/')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
