# Generated by Django 3.2.13 on 2022-04-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='books_covers/'),
        ),
    ]
