# Generated by Django 3.2.13 on 2022-04-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='main/media/books_covers/default.jpg', upload_to='books_covers/'),
        ),
    ]
